[build-system]
requires = ["setuptools >= 60", "wheel", "Cython >= 0.29", "numpy>=2.0"]
build-backend = "setuptools.build_meta"

[project]
name = "crowdposetools"
version = "2.0.1"
description = "crowdposetools with bug fix"
requires-python = ">=3.7"

[tool.setuptools]
packages = ["crowdposetools"]

[tool.setuptools.packages.find]
where = ["crowdposetools"]

[tool.setuptools.ext_modules]
crowdposetools._mask = [
    {
        sources = ["../common/maskApi.c", "crowdposetools/_mask.pyx"],
        include_dirs = ["numpy", "../common"],  # numpy 的 include 路径需要已安装 numpy
        extra_compile_args = ["-Wno-cpp", "-Wno-unused-function", "-std=c99"],
    }
]
